spring:
  application.name: hystrix-turbine-server
server:
  port: 8769
security.basic.enabled: false
turbine:
  aggregator:
    clusterConfig: default
  appConfig: eshop-one-service
  clusterNameExpression: new String("default")
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.18:8761/eureka/